### PR TITLE
JSRS migration

### PR DESCRIPTION
**Pull request by gabrieloliveira41**

### CODE REVIEW

**Comment by gabrieloliveira41** [comment]
Goal verified after changes (1 out of 1 goal total):
- shoe 
find a shoe between $60 and $65
find athletic shoes
Find a shoe for me!
Find a dance shoe less than $85
Find a dance shoe for me!

All resulted in equal intents and equal IDE simulator results after migration comparing to before the migration

**Comment by gabrieloliveira41** [comment]
the migration tool successfully migrated the code, the only fix i did was on the file capsule.bxb line 20 were i updated the viv.money version cause there were a stage 1 deprecation 
image

**Comment by gabrieloliveira41** [comment]
@kangawoo44 @abapayeViv review pls!

**Review by abapayeViv — APPROVED** [review]
LGTM 👍

**Review by kangawoo44 — APPROVED** [review]
LGTM!

**Pull request merged**
